name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        run: curl -L https://nixos.org/nix/install | sh

      - name: Install dependencies
        run: /home/runner/.nix-profile/etc/profile.d/nix.sh develop --command flutter pub get

      - name: Run analyzer
        run: /home/runner/.nix-profile/etc/profile.d/nix.sh develop --command flutter analyze
